/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiProposalsRouteImport } from './routes/api/proposals'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiUsersSyncRouteImport } from './routes/api/users.sync'
import { Route as ApiUsersIncentivesRouteImport } from './routes/api/users.incentives'
import { Route as ApiUsersClaimRouteImport } from './routes/api/users.claim'
import { Route as ApiUsersBindWalletRouteImport } from './routes/api/users.bind-wallet'
import { Route as ApiPublicWalletLookupRouteImport } from './routes/api/public/wallet-lookup'
import { Route as ApiIncentivesGlobalRouteImport } from './routes/api/incentives.global'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicSiweVerifyRouteImport } from './routes/api/public/siwe.verify'
import { Route as ApiPublicSiweNonceRouteImport } from './routes/api/public/siwe.nonce'
import { Route as ApiProposalsIdVoteRouteImport } from './routes/api/proposals.$id.vote'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsRoute = ApiProposalsRouteImport.update({
  id: '/api/proposals',
  path: '/api/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersSyncRoute = ApiUsersSyncRouteImport.update({
  id: '/api/users/sync',
  path: '/api/users/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIncentivesRoute = ApiUsersIncentivesRouteImport.update({
  id: '/api/users/incentives',
  path: '/api/users/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersClaimRoute = ApiUsersClaimRouteImport.update({
  id: '/api/users/claim',
  path: '/api/users/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersBindWalletRoute = ApiUsersBindWalletRouteImport.update({
  id: '/api/users/bind-wallet',
  path: '/api/users/bind-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalletLookupRoute = ApiPublicWalletLookupRouteImport.update({
  id: '/api/public/wallet-lookup',
  path: '/api/public/wallet-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncentivesGlobalRoute = ApiIncentivesGlobalRouteImport.update({
  id: '/api/incentives/global',
  path: '/api/incentives/global',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSiweVerifyRoute = ApiPublicSiweVerifyRouteImport.update({
  id: '/api/public/siwe/verify',
  path: '/api/public/siwe/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiweNonceRoute = ApiPublicSiweNonceRouteImport.update({
  id: '/api/public/siwe/nonce',
  path: '/api/public/siwe/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsIdVoteRoute = ApiProposalsIdVoteRouteImport.update({
  id: '/$id/vote',
  path: '/$id/vote',
  getParentRoute: () => ApiProposalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRoute
  '/api/incentives/global': typeof ApiIncentivesGlobalRoute
  '/api/public/wallet-lookup': typeof ApiPublicWalletLookupRoute
  '/api/users/bind-wallet': typeof ApiUsersBindWalletRoute
  '/api/users/claim': typeof ApiUsersClaimRoute
  '/api/users/incentives': typeof ApiUsersIncentivesRoute
  '/api/users/sync': typeof ApiUsersSyncRoute
  '/api/proposals/$id/vote': typeof ApiProposalsIdVoteRoute
  '/api/public/siwe/nonce': typeof ApiPublicSiweNonceRoute
  '/api/public/siwe/verify': typeof ApiPublicSiweVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRoute
  '/api/incentives/global': typeof ApiIncentivesGlobalRoute
  '/api/public/wallet-lookup': typeof ApiPublicWalletLookupRoute
  '/api/users/bind-wallet': typeof ApiUsersBindWalletRoute
  '/api/users/claim': typeof ApiUsersClaimRoute
  '/api/users/incentives': typeof ApiUsersIncentivesRoute
  '/api/users/sync': typeof ApiUsersSyncRoute
  '/api/proposals/$id/vote': typeof ApiProposalsIdVoteRoute
  '/api/public/siwe/nonce': typeof ApiPublicSiweNonceRoute
  '/api/public/siwe/verify': typeof ApiPublicSiweVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/health': typeof ApiHealthRoute
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRoute
  '/api/incentives/global': typeof ApiIncentivesGlobalRoute
  '/api/public/wallet-lookup': typeof ApiPublicWalletLookupRoute
  '/api/users/bind-wallet': typeof ApiUsersBindWalletRoute
  '/api/users/claim': typeof ApiUsersClaimRoute
  '/api/users/incentives': typeof ApiUsersIncentivesRoute
  '/api/users/sync': typeof ApiUsersSyncRoute
  '/api/proposals/$id/vote': typeof ApiProposalsIdVoteRoute
  '/api/public/siwe/nonce': typeof ApiPublicSiweNonceRoute
  '/api/public/siwe/verify': typeof ApiPublicSiweVerifyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/api/health'
    | '/api/proposals'
    | '/api/transactions'
    | '/api/incentives/global'
    | '/api/public/wallet-lookup'
    | '/api/users/bind-wallet'
    | '/api/users/claim'
    | '/api/users/incentives'
    | '/api/users/sync'
    | '/api/proposals/$id/vote'
    | '/api/public/siwe/nonce'
    | '/api/public/siwe/verify'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/api/health'
    | '/api/proposals'
    | '/api/transactions'
    | '/api/incentives/global'
    | '/api/public/wallet-lookup'
    | '/api/users/bind-wallet'
    | '/api/users/claim'
    | '/api/users/incentives'
    | '/api/users/sync'
    | '/api/proposals/$id/vote'
    | '/api/public/siwe/nonce'
    | '/api/public/siwe/verify'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/api/health'
    | '/api/proposals'
    | '/api/transactions'
    | '/api/incentives/global'
    | '/api/public/wallet-lookup'
    | '/api/users/bind-wallet'
    | '/api/users/claim'
    | '/api/users/incentives'
    | '/api/users/sync'
    | '/api/proposals/$id/vote'
    | '/api/public/siwe/nonce'
    | '/api/public/siwe/verify'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProposalsRoute: typeof ApiProposalsRouteWithChildren
  ApiTransactionsRoute: typeof ApiTransactionsRoute
  ApiIncentivesGlobalRoute: typeof ApiIncentivesGlobalRoute
  ApiPublicWalletLookupRoute: typeof ApiPublicWalletLookupRoute
  ApiUsersBindWalletRoute: typeof ApiUsersBindWalletRoute
  ApiUsersClaimRoute: typeof ApiUsersClaimRoute
  ApiUsersIncentivesRoute: typeof ApiUsersIncentivesRoute
  ApiUsersSyncRoute: typeof ApiUsersSyncRoute
  ApiPublicSiweNonceRoute: typeof ApiPublicSiweNonceRoute
  ApiPublicSiweVerifyRoute: typeof ApiPublicSiweVerifyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals': {
      id: '/api/proposals'
      path: '/api/proposals'
      fullPath: '/api/proposals'
      preLoaderRoute: typeof ApiProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/sync': {
      id: '/api/users/sync'
      path: '/api/users/sync'
      fullPath: '/api/users/sync'
      preLoaderRoute: typeof ApiUsersSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/incentives': {
      id: '/api/users/incentives'
      path: '/api/users/incentives'
      fullPath: '/api/users/incentives'
      preLoaderRoute: typeof ApiUsersIncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/claim': {
      id: '/api/users/claim'
      path: '/api/users/claim'
      fullPath: '/api/users/claim'
      preLoaderRoute: typeof ApiUsersClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/bind-wallet': {
      id: '/api/users/bind-wallet'
      path: '/api/users/bind-wallet'
      fullPath: '/api/users/bind-wallet'
      preLoaderRoute: typeof ApiUsersBindWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wallet-lookup': {
      id: '/api/public/wallet-lookup'
      path: '/api/public/wallet-lookup'
      fullPath: '/api/public/wallet-lookup'
      preLoaderRoute: typeof ApiPublicWalletLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incentives/global': {
      id: '/api/incentives/global'
      path: '/api/incentives/global'
      fullPath: '/api/incentives/global'
      preLoaderRoute: typeof ApiIncentivesGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/siwe/verify': {
      id: '/api/public/siwe/verify'
      path: '/api/public/siwe/verify'
      fullPath: '/api/public/siwe/verify'
      preLoaderRoute: typeof ApiPublicSiweVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/siwe/nonce': {
      id: '/api/public/siwe/nonce'
      path: '/api/public/siwe/nonce'
      fullPath: '/api/public/siwe/nonce'
      preLoaderRoute: typeof ApiPublicSiweNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals/$id/vote': {
      id: '/api/proposals/$id/vote'
      path: '/$id/vote'
      fullPath: '/api/proposals/$id/vote'
      preLoaderRoute: typeof ApiProposalsIdVoteRouteImport
      parentRoute: typeof ApiProposalsRoute
    }
  }
}

interface ApiProposalsRouteChildren {
  ApiProposalsIdVoteRoute: typeof ApiProposalsIdVoteRoute
}

const ApiProposalsRouteChildren: ApiProposalsRouteChildren = {
  ApiProposalsIdVoteRoute: ApiProposalsIdVoteRoute,
}

const ApiProposalsRouteWithChildren = ApiProposalsRoute._addFileChildren(
  ApiProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProposalsRoute: ApiProposalsRouteWithChildren,
  ApiTransactionsRoute: ApiTransactionsRoute,
  ApiIncentivesGlobalRoute: ApiIncentivesGlobalRoute,
  ApiPublicWalletLookupRoute: ApiPublicWalletLookupRoute,
  ApiUsersBindWalletRoute: ApiUsersBindWalletRoute,
  ApiUsersClaimRoute: ApiUsersClaimRoute,
  ApiUsersIncentivesRoute: ApiUsersIncentivesRoute,
  ApiUsersSyncRoute: ApiUsersSyncRoute,
  ApiPublicSiweNonceRoute: ApiPublicSiweNonceRoute,
  ApiPublicSiweVerifyRoute: ApiPublicSiweVerifyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
