import { keccak256, toUtf8Bytes, id, AbiCoder } from 'ethers';
const sel = s => id(s).slice(0,10);
console.log('VAULT_ROLE()', sel('VAULT_ROLE()'));
console.log('grantRole', sel('grantRole(bytes32,address)'));
const R='https://rpc.botchain.ai';
const T='0xA861152Ca3676bcCf7B5FDAFB9eb6A57b9d32d0e';
const call = async (to,data)=>{const r=await fetch(R,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_call',params:[{to,data},'latest']})});return (await r.json());};
const vr = await call(T, sel('VAULT_ROLE()'));
console.log('VAULT_ROLE', vr);
const role = vr.result;
const ac = AbiCoder.defaultAbiCoder();
const calldata = sel('grantRole(bytes32,address)') + ac.encode(['bytes32','address'],[role,'0x3cc0799fB4169A9BB5dA9812Bea23CBa97B989c8']).slice(2);
console.log('calldata', calldata);
console.log('calldataHash', keccak256(calldata));
console.log('hasRole(vault)', await call(T, sel('hasRole(bytes32,address)')+ac.encode(['bytes32','address'],[role,'0x3cc0799fB4169A9BB5dA9812Bea23CBa97B989c8']).slice(2)));
const ZERO='0x'+'0'.repeat(64);
console.log('gov isAdmin', await call(T, sel('hasRole(bytes32,address)')+ac.encode(['bytes32','address'],[ZERO,'0x88A4CC1F5771523baeB83DaEea07D323a3ce9507']).slice(2)));
console.log('reservedGenesis', await call(T, sel('reservedGenesis()')));
console.log('reservedFloors', await call(T, sel('reservedFloors()')));
console.log('committedEpoch', await call(T, sel('committedEpoch()')));
console.log('accruedUnclaimed', await call(T, sel('accruedUnclaimed()')));
console.log('freeBalance', await call(T, sel('freeBalance()')));
// simulate from Safe
const r=await fetch(R,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_estimateGas',params:[{from:'0x88A4CC1F5771523baeB83DaEea07D323a3ce9507',to:T,data:calldata,value:'0x0'}]})});
console.log('estimateGas from Safe', await r.json());
const r2=await fetch(R,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_call',params:[{from:'0x851275569923C62a2EF962EC35bfBb8f1bCbf3dD',to:T,data:calldata},'latest']})});
console.log('deployer call (must revert)', await r2.json());
