import { createClient } from '@supabase/supabase-js';
import { evaluateReleaseFreeze, CURRENT_RELEASE_FREEZE_INPUT, currentCandidateDigest } from '@/lib/deploy/mainnetReleaseFreeze';
import fs from 'node:fs';
const url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const sb = createClient(url, key, { auth: { persistSession: false } });
const { data, error } = await sb.from('mainnet_release_decisions').select('decision_id,action,candidate_digest,approved_value,approved_by_email,approved_at,note').order('approved_at', { ascending: true });
if (error) throw error;
const submissions = (data ?? []).map((r: any) => ({ decisionId: r.decision_id, action: r.action, value: r.approved_value ?? null, approvedByEmail: r.approved_by_email, approvedAt: r.approved_at, note: r.note, candidateDigest: r.candidate_digest }));
const cd = currentCandidateDigest();
const r = evaluateReleaseFreeze({ ...CURRENT_RELEASE_FREEZE_INPUT, submissions, candidateDigest: cd });
console.log('records', submissions.length, 'verdict', r.verdict, r.stagedReadiness, 'digest', cd);
console.log('outstanding', r.outstanding);
console.log('featureOutstanding', r.featureOutstanding);
console.log('deferred', r.deferredNonTechnical);
console.log('findings', r.failClosedFindings);
console.log('manifestHash', r.manifestHash);
console.log('safes', r.safeVerification.map(s=>[s.authority,s.state]));
fs.writeFileSync('contracts/MAINNET_RELEASE_DECISIONS.json', JSON.stringify({ manifestHash: r.manifestHash, manifest: r.manifest }, null, 2) + '\n');
